package org.example.drools.fire

import org.example.drools.web.forward.model.*

rule "When there is a fire turn on the sprinkler"
when
  Fire($room : room)
  $sprinkler : Sprinkler(room == $room, on == false)
then
  modify($sprinkler) { setOn(true) };
  System.out.println("Turn on the sprinkler for room "+$room.getName());
end

rule "When there is no fire turn on the sprinkler"
when
  not Alarm()
  not Fire()
  $sprinkler : Sprinkler(on == true)
then
  modify($sprinkler) { setOn(false) };
  System.out.println("Turn off the sprinkler for room "+$sprinkler.getRoom().getName());
end

rule "Raise the alarm when we have one or more fires"
when
    exists Fire()
then
    insert( new Alarm() );
    System.out.println( "Raise the alarm" );
end

rule "Cancel the alarm when all the fires have gone"
when
    not Fire()
    $alarm : Alarm()
then
    delete( $alarm );
    System.out.println( "Cancel the alarm" );
end


rule "Status output when things are ok"
when
    not Alarm()
    not Sprinkler( on == true )
then
    System.out.println( "Everything is ok" );
end